@GestaHogar.Api_HostAddress = https://localhost:7224


GET {{GestaHogar.Api_HostAddress}}/api/products

###

GET {{GestaHogar.Api_HostAddress}}/api/userproducts

###

@id=0
GET {{GestaHogar.Api_HostAddress}}/api/userproducts/{{id}}

###
